inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  TargetRubyVersion: 2.6
  Exclude:
    - config/**/*
    - tmp/**/*
    - Capfile
    - Gemfile
    - Rakefile

# EOL is handled by git settings
Layout/EndOfLine:
  Enabled: false

# Disable some common cops for tests
Style/Documentation:
  Exclude:
    - test/**/*
Metrics/AbcSize:
  Exclude:
    - test/**/*
Metrics/MethodLength:
  Exclude:
    - test/**/*

# Just enough
Layout/LineLength:
  Max: 100
