inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
  TargetRubyVersion: 2.6
  Exclude:
    - config/**/*
    - tmp/**/*
    - Capfile
    - Gemfile
    - Rakefile

# EOL is handled by git settings
Layout/EndOfLine:
  Enabled: false

# Just enough
Layout/LineLength:
  Max: 100

# Disable some common cops for tests
Style/Documentation:
  Exclude:
    - test/**/*
Metrics/AbcSize:
  Exclude:
    - test/**/*
Metrics/MethodLength:
  Max: 15 # Extended limit of lines in method
  Exclude:
    - test/**/*

